spring:
  datasource:
    url: jdbc:postgresql://prod_postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  minio:
    url: http://prod_minio:9000
    secret-key: ${MINIO_SECRET_KEY}
    access-key: ${MINIO_ACCESS_KEY}
    bucket: photos
