spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/mydatabase
    username: myuser
    password: mypassword
    driverClassName: org.postgresql.Driver
  minio:
    url: http://localhost:9000
    secret-key: minioadmin
    access-key: minioadmin
    bucket: photos
app:
  init-db: true

