name: Deploy to remote server

on:
  - workflow_dispatch

jobs:
  deploy_staging:
    environment: prod
    name: 'Deploy to staging'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Start Docker Compose Deployment'
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
          ssh_public_key: ${{secrets.SSH_PUBLIC_KEY}}
          stack_file_name: docker/docker-compose.yml
          docker_login_password: ${{secrets.DOCKER_TOKEN}}
          docker_login_user: ${{vars.DOCKER_USER}}
          docker_login_registry: ghcr.io
          args: --profile prod up -d
