name: Deploy to remote server

on:
  - workflow_dispatch

jobs:
  deploy_to_server:
    environment: prod
    name: 'Deploy to remote'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Set or update environment variables on remote'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            whoami
            printenv
            export \ 
            POSTGRES_PORT="${{vars.POSTGRES_PORT}}" \
            POSTGRES_DB="${{vars.POSTGRES_DB}}" \
            POSTGRES_USER="${{vars.POSTGRES_USER}}" \
            POSTGRES_PASSWORD="${{vars.POSTGRES_PASSWORD}}" \
            MINIO_ACCESS_KEY="${{vars.MINIO_ACCESS_KEY}}" \
            MINIO_SECRET_KEY="${{vars.MINIO_SECRET_KEY}}"
      - name: 'Start Docker Compose Deployment'
        uses: FarisZR/docker-compose-gitops-action@v1
        with:
          remote_docker_host: ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
          ssh_public_key: ${{secrets.SSH_PUBLIC_KEY}}
          compose_file_path: docker/docker-compose.yml
          docker_login_password: ${{secrets.DOCKER_TOKEN}}
          docker_login_user: ${{vars.DOCKER_USER}}
          docker_login_registry: ghcr.io
          args: --profile prod up -d --force-recreate
