name: Deploy to remote server

on:
  - workflow_dispatch

jobs:
  deploy_to_server:
    environment: prod
    name: 'Deploy to remote'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Deploy Docker Compose'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            export \ 
            POSTGRES_PORT="${{vars.POSTGRES_PORT}}" \
            POSTGRES_DB="${{vars.POSTGRES_DB}}" \
            POSTGRES_USER="${{vars.POSTGRES_USER}}" \
            POSTGRES_PASSWORD="${{vars.POSTGRES_PASSWORD}}" \
            MINIO_ACCESS_KEY="${{vars.MINIO_ACCESS_KEY}}" \
            MINIO_SECRET_KEY="${{vars.MINIO_SECRET_KEY}}"
            docker compose --profile prod up -d --force-recreate
